---
version: "2.1"
services:
  apache2:
    image: ubuntu/apache2
    container_name: mc_dynmap
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Singapore/Singapore
    volumes:
      - .\www\web:/var/www/web:ro
      - .\apache2_conf\conf-available:/etc/apache2/conf-available:ro
      - .\apache2_conf\mods-available:/etc/apache2/mods-available:ro
      - .\apache2_conf\sites-available:/etc/apache2/sites-available:ro
      - .\apache2_conf\apache2.conf:/etc/apache2/apache2.conf:ro
      - .\apache2_conf\ports.conf:/etc/apache2/ports.conf:ro
    ports:
      - 8080:80
    restart: unless-stopped