services:
  dynmap_standalone_web:
    image: php:apache
    container_name: apache2
    environment:
      - TZ=Singapore/Singapore
    volumes:
      - ./web:/var/www/html:ro  # Adjust the file location to your dynamp web directory
    ports:
      - 8080:80
    restart: unless-stopped